### ISSUE TITLE
all-contributors

### ISSUE THREAD

**Issue by gruselhaus** [pegabot/pegabot#41]
@all-contributors please add @gruselhaus for code, infra, projectManagement and business

**Comment by gruselhaus** [comment]
@all-contributors please add @gruselhaus for code, infra, projectManagement and business

**Comment by gruselhaus** [comment]
@zeitiger @cnh003 fügt euch gern hinzu

**Comment by cnh003** [comment]
@all-contributors please add @cnh003 for code
